# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo This is a private azure devops project. The pipeline is visible on github, but you cannot see the pipeline on dev.azure.com.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
