name: solombot CI/CD pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Build and publish to DockerHub
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: solomson/solombot
        username: solomson
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest, ${{ github.sha }}"

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Update Azure webapp'
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'solombot'
        images: 'solomson/solombot:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout