name: solombot CI/CD pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Build and publish to DockerHub
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: solomson/solombot
        username: solomson
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest, ${{ github.sha }}"

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.76
        inlineScript: |
          az container restart --name solombot \
          --resource-group solombot-rg --no-wait
    
    - name: Azure logout
      run: |
        az logout